# Generated by Django 5.2.1 on 2025-05-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles_images/'),
        ),
    ]
