# Generated by Django 5.2.1 on 2025-05-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayertime',
            name='day',
            field=models.DateField(),
        ),
    ]
