# Generated by Django 5.2.1 on 2025-05-20 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0003_alter_prayertime_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayertime',
            name='day',
        ),
        migrations.AddField(
            model_name='prayertime',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 5, 20)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayertime',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
