# Generated by Django 5.2.1 on 2025-05-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_mosque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='address',
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
