# Generated by Django 5.2.1 on 2025-05-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_remove_mosque_address_alter_mosque_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mosque',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('orient', 'Orient'), ('afrique', 'Afrique'), ('europe', 'Europe'), ('amerique', 'Amérique')], default='afrique', max_length=20),
        ),
    ]