# Generated by Django 5.2.1 on 2025-05-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tous', 'Tout'), ('orient', 'Orient'), ('afrique', 'Afrique'), ('europe', 'Europe'), ('amerique', 'Amérique'), ('monde', 'Monde')], default='afrique', max_length=20),
        ),
    ]
