# Generated by Django 5.2.1 on 2025-05-19 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0007_comment_favorite_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre descriptif de la bannière', max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('url', models.URLField(blank=True, help_text='Lien sur lequel la bannière redirige', null=True)),
                ('category', models.CharField(blank=True, help_text='Catégorie ciblée (ex: Monde, Afrique, etc.)', max_length=50, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text="Date de fin d'affichage (optionnel)", null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='article',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='article',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
